import { Component, input } from '@angular/core';
import { PiyingView } from '@piying/view-angular';
import { FieldGlobalConfig } from './define';
import {
  actionSchema,
  arraySchema,
  booleanSchema,
  componentUseSchema,
  contextSchema,
  contextSchemaContext,
  contextSchemaOptions,
  defaultSchema,
  layoutSchema,
  looseObjectSchema,
  looseTupleSchema,
  nfcSchema,
  nestedSchema,
  numberSchema,
  objectSchema,
  objectGroupDefaultSchema,
  objectGroupLooseSchema,
  objectGroupStrictSchema,
  objectGroupVirtualModeSchema,
  objectGroupEmptyValueSchema,
  objectWithRestSchema,
  picklistSchema,
  rawSchema,
  recordSchema,
  selectorlessSchema,
  stringSchema,
  tabsGroupSchema,
  tupleSchema,
  tupleWithRestSchema,
  validGroupSchema,
  complexNestingSchema,
  complexArraySchema,
  complexTupleSchema,
  complexRecordSchema,
  complexIntersectSchema,
  complexUnionSchema,
  recordBasicSchema,
  formUseLayoutSchema,
  formUseTabsGroupSchema,
  formUseValidGroupSchema,
  formUseFilterGroupSchema,
  formUseScrollGroupSchema,
  recordLabelSchema,
  recordConfigSchema,
  recordTranslationSchema,
  recordGroupKeyValueSchema,
  recordValidationSchema,
  recordCompleteSchema,
  basicFormConfigSchema,
  basicDefaultValueSchema,
  basicDefaultValueFormSchema,
  basicNullableSchema,
  basicRequiredSchema,
  basicRequiredOverrideSchema,
  basicDisabledSchema,
  basicValidatorSchema,
  transformDemoSchema,
  transformToModelSchema,
  transformToViewSchema,
  transformPipeSchema,
  transformBasicSchema,
  transformFlattenSchema,
  transformArraySchema,
  eventsSchema,
  apiCssClassSchema,
  apiAttributesSchema,
  dynamicHideWhenSchema,
  dynamicHideDisabledSchema,
  dynamicDisableWhenSchema,
  dynamicValueChangeSchema,
  dynamicPaymentSchema,
  dynamicSubmittedSchema,
  dynamicCascadeSchema,
  dynamicUpdateOtherSchema,
  arrayResetSchema,
  arrayShrinkSchema,
  arrayMarkSchema,
  arrayEmptyValueSchema,
  arrayTupleSchema,
  arrayTupleWithRestSchema,
  arrayCompleteSchema,
  validationDemoSchema,
  validationSyncSchema,
  validationAsyncSchema,
  validationCombinedSchema,
  validationCompareSchema,
  validationConditionalSchema,
  validationDynamicErrorSchema,
  complexCombinedSchema,
  controlGroupDefaultSchema,
  controlGroupAsControlSchema,
  controlGroupAsVirtualSchema,
  transformCompleteSchema,
  formUseValueChangeSchema,
  formUseDisableWhenSchema,
  formUseArrayRwSchema,
  formUseUpdateOtherSchema,
  formUseValidatorSchema,
  formUseCascadeSchema,
  basicFieldDisableWhenSchema,
} from './definition';
import * as v from 'valibot';

/**
 * 通用「定义 → 表单」演示组件。
 * 通过 `name` 选择要展示的定义，结合全局 FieldGlobalConfig 自动渲染为对应表单。
 * schema 在组件内部引用，避免经 Astro 序列化丢失 Valibot 内部方法。
 */
const schemas: Record<string, v.BaseSchema<any, any, any>> = {
  string: stringSchema,
  number: numberSchema,
  boolean: booleanSchema,
  picklist: picklistSchema,
  object: objectSchema,
  looseObject: looseObjectSchema,
  objectWithRest: objectWithRestSchema,
  'object-group-default': objectGroupDefaultSchema,
  'object-group-loose': objectGroupLooseSchema,
  'object-group-strict': objectGroupStrictSchema,
  'object-group-virtual-mode': objectGroupVirtualModeSchema,
  'object-group-empty-value': objectGroupEmptyValueSchema,
  record: recordSchema,
  array: arraySchema,
  tuple: tupleSchema,
  looseTuple: looseTupleSchema,
  tupleWithRest: tupleWithRestSchema,
  default: defaultSchema,
  nested: nestedSchema,
  'component-use': componentUseSchema,
  nfc: nfcSchema,
  action: actionSchema,
  events: eventsSchema,
  'api-css-class': apiCssClassSchema,
  'api-attributes': apiAttributesSchema,
  context: contextSchema,
  raw: rawSchema,
  selectorless: selectorlessSchema,
  'tabs-group': tabsGroupSchema,
  layout: layoutSchema,
  'valid-group': validGroupSchema,
  'complex-nesting': complexNestingSchema,
  'complex-array': complexArraySchema,
  'complex-tuple': complexTupleSchema,
  'complex-record': complexRecordSchema,
  'complex-intersect': complexIntersectSchema,
  'complex-union': complexUnionSchema,
  'record-basic': recordBasicSchema,
  'form-use-layout': formUseLayoutSchema,
  'form-use-tabs-group': formUseTabsGroupSchema,
  'form-use-valid-group': formUseValidGroupSchema,
  'form-use-filter-group': formUseFilterGroupSchema,
  'form-use-scroll-group': formUseScrollGroupSchema,
  'record-label': recordLabelSchema,
  'record-config': recordConfigSchema,
  'record-translation': recordTranslationSchema,
  'record-group-key-value': recordGroupKeyValueSchema,
  'record-validation': recordValidationSchema,
  'record-complete': recordCompleteSchema,
  'basic-form-config': basicFormConfigSchema,
  'basic-default-value': basicDefaultValueSchema,
  'basic-default-value-form': basicDefaultValueFormSchema,
  'basic-nullable': basicNullableSchema,
  'basic-required': basicRequiredSchema,
  'basic-required-override': basicRequiredOverrideSchema,
  'basic-disabled': basicDisabledSchema,
  'basic-validator': basicValidatorSchema,
  'transform-demo': transformDemoSchema,
  'transform-to-model': transformToModelSchema,
  'transform-to-view': transformToViewSchema,
  'transform-pipe': transformPipeSchema,
  'transform-basic': transformBasicSchema,
  'transform-flatten': transformFlattenSchema,
  'transform-array': transformArraySchema,
  'dynamic-hide-when': dynamicHideWhenSchema,
  'dynamic-hide-disabled': dynamicHideDisabledSchema,
  'dynamic-disable-when': dynamicDisableWhenSchema,
  'dynamic-value-change': dynamicValueChangeSchema,
  'dynamic-payment': dynamicPaymentSchema,
  'dynamic-submitted': dynamicSubmittedSchema,
  'dynamic-cascade': dynamicCascadeSchema,
  'dynamic-update-other': dynamicUpdateOtherSchema,
  'array-reset': arrayResetSchema,
  'array-shrink': arrayShrinkSchema,
  'array-mark': arrayMarkSchema,
  'array-empty-value': arrayEmptyValueSchema,
  'array-tuple': arrayTupleSchema,
  'array-tuple-with-rest': arrayTupleWithRestSchema,
  'array-complete': arrayCompleteSchema,
  'validation-demo': validationDemoSchema,
  'validation-sync': validationSyncSchema,
  'validation-async': validationAsyncSchema,
  'validation-combined': validationCombinedSchema,
  'validation-compare': validationCompareSchema,
  'validation-conditional': validationConditionalSchema,
  'validation-dynamic-error': validationDynamicErrorSchema,
  'complex-combined': complexCombinedSchema,
  'control-group-default': controlGroupDefaultSchema,
  'control-group-as-control': controlGroupAsControlSchema,
  'control-group-as-virtual': controlGroupAsVirtualSchema,
  'transform-complete': transformCompleteSchema,
  'form-use-value-change': formUseValueChangeSchema,
  'form-use-disable-when': formUseDisableWhenSchema,
  'form-use-array-rw': formUseArrayRwSchema,
  'form-use-update-other': formUseUpdateOtherSchema,
  'form-use-validator': formUseValidatorSchema,
  'form-use-cascade': formUseCascadeSchema,
  'basic-field-disable-when': basicFieldDisableWhenSchema,
};

const defaultModels: Record<string, unknown> = {
  array: { list: ['v1'] },
  looseObject: { k1: 'v1', k2: 2 },
  objectWithRest: { k1: 'v1', k2: 2 },
  'object-group-default': { k1: 'v1', extraKey: 'schema 未定义的键' },
  'object-group-loose': { k1: 'v1', extraKey: 'schema 未定义的键' },
  'object-group-strict': { k1: 'v1', extraKey: 'schema 未定义的键' },
  'object-group-virtual-mode': { a: '11' },
  'object-group-empty-value': { profile: {} },
  record: { o1: { k1: 'v1' } },
  tuple: { list: ['v1'] },
  looseTuple: { list: ['v1', 'v2'] },
  tupleWithRest: { list: ['v1', 'v2'] },
  'complex-nesting': {
    user: { name: '张三', address: { city: '北京', street: '长安街' } },
  },
  'complex-array': { tags: ['v1', 'v2'], scores: [1, 2] },
  'complex-tuple': { position: [1, 2] },
  'complex-record': { metadata: { k1: 'v1' }, scores: { s1: 1 } },
  'complex-intersect': { name: '张三', age: 25 },
  'complex-union': { value: 'v1' },
  'record-basic': { metadata: { k1: 'v1' }, scores: { s1: 1 } },
  'form-use-layout': { input1: '', input2: '', input3: '', input4: '' },
  'form-use-tabs-group': { k1: '', k2: '', k3: '', k4: '' },
  'form-use-valid-group': { k1: '', k2: '' },
  'form-use-filter-group': {},
  'form-use-scroll-group': {},
  'record-label': { labels: { 研发部: 'P7' } },
  'record-config': { config: { theme: 'dark', count: 3 } },
  'record-translation': { translations: { zh: '你好' } },
  'record-group-key-value': { name: '张三' },
  'record-validation': { metadata: { score: 5 } },
  'record-complete': {
    metadata: { k1: 'v1' },
    settings: { darkMode: true },
    teamMembers: { zhang: { name: '张三', role: '开发' } },
  },
  'basic-form-config': { name: '张三' },
  'basic-default-value': { name: '默认名称' },
  'basic-default-value-form': { age: 18 },
  'basic-nullable': { name: '张三', email: 'a@b.com' },
  'basic-required': { name: '张三', email: 'a@b.com' },
  'basic-required-override': { tags: ['v1', 'v2'] },
  'basic-disabled': { readonlyField: '只读值' },
  'basic-validator': { password: 'abc' },
  'transform-demo': { name: '' },
  'transform-to-model': { price: '19.99' },
  'transform-to-view': { date: '2024-01-01T00:00:00.000Z' },
  'transform-pipe': { search: 'AbC' },
  'transform-basic': { age: '25' },
  'transform-flatten': { fullName: '张三' },
  'transform-array': { tags: ['a', 'b'] },
  'dynamic-hide-when': { showExtra: true, extraField: '额外字段' },
  'dynamic-hide-disabled': { enable: true, name: '张三' },
  'dynamic-disable-when': { isActive: true, name: '张三' },
  'dynamic-value-change': { source: '', target: '' },
  'dynamic-payment': {
    paymentMethod: 'alipay',
    alipayAccount: '',
    wechatAccount: '',
    cardNumber: '',
  },
  'dynamic-submitted': { isSubmitted: false, name: '张三' },
  'dynamic-cascade': { k1: true, k2: false, k3: true },
  'dynamic-update-other': {
    mode: 'data1',
    o1: { k1: '', k2: '' },
    o2: { k3: '', k4: '' },
  },
  'array-reset': ['default1', 'default2'],
  'array-shrink': ['a', 'b', 'c'],
  'array-mark': [1, 'v2'],
  'array-empty-value': { tags: [] },
  'array-tuple': ['v1', 2],
  'array-tuple-with-rest': ['v1', 0, 1],
  'array-complete': {
    tags: ['a', 'b'],
    scores: [0, 0],
    position: [1, 2],
    coordinates: ['v1', 3],
    groups: [{ name: '张三' }],
  },
  'validation-demo': { password: '', confirmPassword: '' },
  'validation-sync': { password: 'abc123' },
  'validation-async': { username: '' },
  'validation-combined': { email: 'test@test.com' },
  'validation-compare': { password: '12345678', confirmPassword: '87654321' },
  'validation-conditional': { hasAddress: true, address: '' },
  'validation-dynamic-error': { age: 25 },
  'complex-combined': {
    name: '',
    address: { city: '', details: { street: '', zipCode: '' } },
    positions: [[1, 2]],
    metadata: {},
    profile: { bio: '', website: '' },
    identifier: 'x',
  },
  'control-group-default': { address: { city: '上海', street: '南京路' } },
  'control-group-as-control': { address: { city: '上海', street: '南京路' } },
  'control-group-as-virtual': { name: '张三', age: 25 },
  'transform-complete': { search: '', price: '', birthDate: '', score: '80' },
  'form-use-value-change': { k1: '' },
  'form-use-disable-when': {
    enable: true,
    value: { input1: '', input2: '', input3: '', input4: '' },
  },
  'form-use-array-rw': { list: ['v1', 'v2'] },
  'form-use-update-other': {
    list: 'data1',
    o1: { k1: '', k2: '' },
    o2: { k3: '', k4: '' },
  },
  'form-use-validator': { k1: '' },
  'form-use-cascade': { k1: true, k2: false, k3: true, k4: false },
  'basic-field-disable-when': { isActive: true, name: '张三' },
};

@Component({
  selector: 'schema-demo',
  standalone: true,
  template: `
    <piying-view
      [schema]="schema()"
      [model]="model()"
      [options]="options()"
    ></piying-view>
  `,
  imports: [PiyingView],
  host: {
    class: 'not-content',
  },
})
export class SchemaDemoComponent {
  name = input('string');
  modelInput = input<unknown>();

  options() {
    if (this.name() === 'context') {
      return contextSchemaOptions;
    }
    return { fieldGlobalConfig: FieldGlobalConfig };
  }

  schema() {
    return schemas[this.name()];
  }

  model() {
    if (this.name() === 'context') {
      return undefined;
    }
    return this.modelInput() ?? defaultModels[this.name()];
  }
}
