name: docs

on:
  push:
    branches: [main]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: 拉取仓库
        uses: actions/checkout@v7
      - name: 安装 Node
        uses: actions/setup-node@v7
        with:
          node-version-file: .nvmrc
      - name: 安装 pnpm
        uses: pnpm/action-setup@v6
        with:
          version: '11'
      - name: 安装依赖1
        run: pnpm install
      - name: 安装依赖2
        run: pnpm install
        working-directory: nova-docs
      - name: 构建文档站点
        run: npm run build:docs
      - name: 上传制品
        id: deployment
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./nova-docs/dist

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: 部署到 GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
